// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TechMoveGLMS.Data;

#nullable disable

namespace TechMoveGLMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.Client", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ContactDetails").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Region").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Clients");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.Contract", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("ClientId").HasColumnType("int");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<string>("ServiceLevel").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("SignedAgreementPath").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("ClientId");
                b.ToTable("Contracts");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.ServiceRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("ContractId").HasColumnType("int");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ServiceLevel").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("LocalCost").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("ContractId");
                b.ToTable("ServiceRequests");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.Contract", b =>
            {
                b.HasOne("TechMoveGLMS.Models.Entities.Client", "Client")
                    .WithMany("Contracts")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Client");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.ServiceRequest", b =>
            {
                b.HasOne("TechMoveGLMS.Models.Entities.Contract", "Contract")
                    .WithMany("ServiceRequests")
                    .HasForeignKey("ContractId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Contract");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.Client", b =>
            {
                b.Navigation("Contracts");
            });

            modelBuilder.Entity("TechMoveGLMS.Models.Entities.Contract", b =>
            {
                b.Navigation("ServiceRequests");
            });
                #pragma warning restore 612, 618
        }
    }
}